### ISSUE TITLE
Gas Issues - Not using the value I am setting.

### ISSUE THREAD

**Issue by deathhopes** [uniswap-python/uniswap-python#114] opened 2021-06-11 07:37 UTC
`uniswap_wrapper = Uniswap(my_wallet, private_key, version=2, provider = provider, max_slippage=slippage, web3 = web3.eth.setGasPriceStrategy(Web3.toWei(gasValue, 'gwei')))`

gasValue = 50

I have utilized the gas strategy per the docs, but have turned it into a one liner since I don't need anything fancy. I'm simply setting the gas manually and not based off any special circumstances. I also did follow the exact same structure from the docs in this below link, but yielded the same result. I have also checked all previous gas issues on this forum and have not found anything similar to my issue.

https://web3py.readthedocs.io/en/stable/gas_price.html

With that being said, when I am checking the transactions I make through etherscan after a swap it is not utilizing the 50 gwei I have set. Instead it's usually just around 10. 

Is there any guidance that you could provide on this matter?

**Comment by ErikBjare** [comment] 2021-06-11 09:06
You're passing the wrong thing to `web3`. 

You need to initialize a Web3 object (with your `provider`), set the gas price strategy on it, and then pass it as the `web3` parameter. Don't pass both `provider` and `web3` to the constructor.

**Comment by ErikBjare** [comment] 2021-06-11 09:08
Duplicate of https://github.com/uniswap-python/uniswap-python/issues/34

Closing.

**Closed by ErikBjare** 2021-06-11 09:08 UTC

**Comment by ErikBjare** [comment] 2021-06-11 10:10
Note that `web3.eth.setGasPriceStrategy(Web3.toWei(gasValue, 'gwei'))` is also most likely incorrect. 

You need to pass a function defining the strategy, as they describe in the docs.

**Comment by deathhopes** [comment] 2021-07-05 21:12
Hi. Thank you for your previous guidance.

I've been trying to solve the issue still on my own for a while now but am at a different stage.

`def value_based_gas_price_strategy(web3, gasValue):
    return Web3.toWei(gasValue, 'gwei')

w3 = Web3(Web3.HTTPProvider(web3, request_kwargs={"timeout": 60}))
w3 = w3.eth.set_gas_price_strategy(value_based_gas_price_strategy)
uniswap_wrapper = Uniswap(my_wallet, private_key, provider = provider, web3 = w3, version=2, max_slippage=slippage)  # pass version=2 to use Uniswap v2
`

I have recreated my code through the documents but it seems the gas value is still being automatically set. 

My gasValue variable is being set by taking user input. So if they typed 50, it should have set 50 gas to the transaction. It seems my def is being ignored.

**Comment by ErikBjare** [comment] 2021-07-05 21:27
Still not correct, function signature of strategy is:

```
def value_based_gas_price_strategy(web3, transaction_params):
   ... 
```

So you can't have `gasPrice` as the second parameter, because it will be called with the tx params. Pass it through a function closure or using a global variable.

**Comment by deathhopes** [comment] 2021-07-06 00:57
> 
> 
> Still not correct, function signature of strategy is:
> 
> ```python
> def value_based_gas_price_strategy(web3, transaction_params):
>    ... 
> ```
> 
> So you can't have `gasPrice` as the second parameter, because it will be called with the tx params. Pass it through a function closure or using a global variable.
> 
> Also: Why are you passing both provider and web3 to the Uniswap constructor? That may not be well defined. Try removing the `provider` keyword argument.
> 
> Edit: Had a look and should be fine to have both, but `provider` won't be used.


Finally got it fully working. It is as you said, I declared a global variable and fixed up the invalid transaction params.

I have also removed the provider since it's kinda redundant. Thank you so much for your help.

**Comment by ErikBjare** [comment] 2021-07-06 14:34
@deathhopes Nice to see you got it working!

Re canceling transactions: The only way is to submit a new tx with the same nonce but a higher gas price. But even that doesn't guarantee the tx will get cancelled, see: https://ethereum.stackexchange.com/a/31300/2285

Can't give any code examples for how to do this with Web3py, but that's the principle which applies.

**Comment by mostar** [comment] 2023-04-18 09:42
> > Still not correct, function signature of strategy is:
> > ```python
> > def value_based_gas_price_strategy(web3, transaction_params):
> >    ... 
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > So you can't have `gasPrice` as the second parameter, because it will be called with the tx params. Pass it through a function closure or using a global variable.
> > Also: Why are you passing both provider and web3 to the Uniswap constructor? That may not be well defined. Try removing the `provider` keyword argument.
> > Edit: Had a look and should be fine to have both, but `provider` won't be used.
> 
> Finally got it fully working. It is as you said, I declared a global variable and fixed up the invalid transaction params.
> 
> I have also removed the provider since it's kinda redundant. Thank you so much for your help.

I fail to implement it, Can you please share this part of you code?
