### ISSUE TITLE
web3.exceptions.ExtraDataLengthError: The field extraData is 97 bytes, but should be 32. It is quite likely that you are connected to a POA chain.

### ISSUE THREAD

**Issue by BlackTurtle123** [uniswap-python/uniswap-python#216] opened 2021-12-15 10:32 UTC
**Describe the bug**
I am trying to connect to quickswap

`from uniswap import Uniswap
from web3 import Web3, HTTPProvider

private_key = "xxxxxxxxxxxxxxxxxxxxxxxx"
w3 = Web3(HTTPProvider('https://rpc-mainnet.matic.network'))
acct = w3.eth.account.privateKeyToAccount(private_key)

address = Web3.toChecksumAddress(acct.address)  # or None if you're not going to make transactions
private_key =  acct.privateKey # or None if you're not going to make transactions
version = 2  # specify which version of Uniswap to use
provider = "https://rpc-mainnet.matic.network"  # can also be set through the environment variable `PROVIDER`
router_contract_addr = "0xa5E0829CaCEd8fFDD4De3c43696c57F7D7A678ff"
factory_contract_addr = "0x5757371414417b8C6CAad45bAeF941aBc7d3Ab32"
quickswap = Uniswap(address=address, private_key=private_key, version=version,
                    factory_contract_addr=factory_contract_addr,
                    router_contract_addr=router_contract_addr,
                    provider=provider)

pair_contract_addr = "0x76db81E10af2Dd38258B08129238cD2Cf3CB3300"

EGG = Web3.toChecksumAddress("0x51de72b17c7bd12e9e6d69eb506a669eb6b5249e")
USDT = Web3.toChecksumAddress("0xc2132d05d31c914a87c6611c10748aeb04b58e8f")

qty = 1*10**quickswap.get_token(EGG).decimals

EGG_USDT = quickswap.get_price_input(EGG, USDT, qty, route=[EGG,USDT])
print(EGG_USDT)
TRADE = quickswap.make_trade(EGG, USDT, 1*10**18, slippage=0.10)  # sell 1 EGG for USDT`

I had to override the default router with in the library to make that part working, 
`No route specified, assuming route: ['0x51dE72b17c7bD12E9E6d69eb506a669EB6b5249E', '0xc2132D05D31c914a87C6611C10748AEb04B58e8F']
`

but I am now stuck with following error

`web3.exceptions.ExtraDataLengthError: The field extraData is 97 bytes, but should be 32. It is quite likely that you are connected to a POA chain. Refer to`

**Comment by BlackTurtle123** [comment] 2021-12-15 11:24
I could work around this by 


w3.middleware_onion.inject(geth_poa_middleware, layer=0)
quickswap = Uniswap(address=address, private_key=private_key, version=version,
                    factory_contract_addr=factory_contract_addr,
                    router_contract_addr=router_contract_addr,
                    provider=provider, web3=w3)
                    
                    
However this still bring me to an error ValueError: {'code': -32000, 'message': 'invalid sender'}

**Comment by liquid-8** [comment] 2021-12-15 12:46
First, that's not a bug actually because Matic is a different network. There is no need to add this middleware on the ETH mainnet. Your workaround is totally fine. In fact, that's how it is supposed to be.

I personally use the next endpoint there:
https://rpc-mainnet.maticvigil.com/
Not sure if it is essential to use this RPC exactly, but I can confirm it is operates fine.

Next, from what I see, the mentioned pool is a direct one. At the moment, there is no support for making swaps in this scenario as `make_trade()` just has no `route` parameter. I'm going to add this feature in the next few days but can not guarantee any exact terms. So you can wait for an update or add this feature yourself.

**Comment by BlackTurtle123** [comment] 2021-12-15 12:58
> Next, from what I see, the mentioned pool is a direct one. At the moment, there is no support for making swaps in this scenario as `make_trade()` just has no `route` parameter. I'm going to add this feature in the next few days but can not guarantee any exact terms. So you can wait for an update or add this feature yourself.

I did hack the library to make it the direct route, however i get this error

> However this still bring me to an error `ValueError: {'code': -32000, 'message': 'invalid sender'}`

**Comment by liquid-8** [comment] 2021-12-15 16:02
Provide more info then. Post whole code, just remove private key and wallet address. Post full exception trace log. That should work actually, can not say more w/o mentioned stuff.

**Comment by BlackTurtle123** [comment] 2021-12-15 16:07
> Provide more info then. Post whole code, just remove private key and wallet address. Post full exception trace log. That should work actually, can not say more w/o mentioned stuff.

`from uniswap import Uniswap
from web3 import Web3, HTTPProvider
from web3.middleware import geth_poa_middleware

private_key = "xxxxxxxxxxxxxxxxx"
w3 = Web3(HTTPProvider('https://rpc-mainnet.maticvigil.com'))
acct = w3.eth.account.privateKeyToAccount(private_key)
w3.middleware_onion.inject(geth_poa_middleware, layer=0)

address = Web3.toChecksumAddress(acct.address)  # or None if you're not going to make transactions
print(address)

private_key =  acct.privateKey # or None if you're not going to make transactions
version = 2  # specify which version of Uniswap to use
provider = "https://rpc-mainnet.maticvigil.com"  # can also be set through the environment variable `PROVIDER`
router_contract_addr = "0xa5E0829CaCEd8fFDD4De3c43696c57F7D7A678ff"
factory_contract_addr = "0x5757371414417b8C6CAad45bAeF941aBc7d3Ab32"
quickswap = Uniswap(address=address, private_key=private_key, version=version,
                    factory_contract_addr=factory_contract_addr,
                    router_contract_addr=router_contract_addr,
                    provider=provider, web3=w3)



pair_contract_addr = "0x76db81E10af2Dd38258B08129238cD2Cf3CB3300"

# Some token addresses we'll be using later in this guide
EGG = Web3.toChecksumAddress("0x51de72b17c7bd12e9e6d69eb506a669eb6b5249e")
USDT = Web3.toChecksumAddress("0xc2132d05d31c914a87c6611c10748aeb04b58e8f")


qty = 1*10**quickswap.get_token(EGG).decimals

EGG_USDT = quickswap.get_price_input(EGG, USDT, qty, route=[EGG,USDT])
print(EGG_USDT)
TRADE = quickswap.make_trade(EGG, USDT, 1*10**18, slippage=0.10)  # sell 1 EGG for USDT
#TRADE2 = quickswap.make_trade(USDT, EGG, 1*10**6)  # sell 1 USDT for EGG
print(TRADE)
#print(TRADE2)`




`
No route specified, assuming route: ['0x51dE72b17c7bD12E9E6d69eb506a669EB6b5249E', '0xc2132D05D31c914a87C6611C10748AEb04B58e8F']

Traceback (most recent call last):
  File "/home/bnagtega/.PyCharm2019.1/config/scratches/scratch_14.py", line 36, in <module>
    TRADE = quickswap.make_trade(EGG, USDT, 1*10**18, slippage=0.10)  # sell 1 EGG for USDT
  File "/home/bnagtega/.local/lib/python3.9/site-packages/uniswap/decorators.py", line 30, in approved
    return method(self, *args, **kwargs)
  File "/home/bnagtega/.local/lib/python3.9/site-packages/uniswap/uniswap.py", line 407, in make_trade
    return self._token_to_token_swap_input(
  File "/home/bnagtega/.local/lib/python3.9/site-packages/uniswap/uniswap.py", line 685, in _token_to_token_swap_input
    return self._build_and_send_tx(
  File "/home/bnagtega/.local/lib/python3.9/site-packages/uniswap/uniswap.py", line 1101, in _build_and_send_tx
    return self.w3.eth.send_raw_transaction(signed_txn.rawTransaction)
  File "/home/bnagtega/.local/lib/python3.9/site-packages/web3/eth.py", line 722, in send_raw_transaction
    return  self._send_raw_transaction(transaction)
  File "/home/bnagtega/.local/lib/python3.9/site-packages/web3/module.py", line 57, in caller
    result = w3.manager.request_blocking(method_str,
  File "/home/bnagtega/.local/lib/python3.9/site-packages/web3/manager.py", line 198, in request_blocking
    return self.formatted_response(response,
  File "/home/bnagtega/.local/lib/python3.9/site-packages/web3/manager.py", line 171, in formatted_response
    raise ValueError(response["error"])
ValueError: {'code': -32000, 'message': 'invalid sender'}

Process finished with exit code 1`

**Comment by liquid-8** [comment] 2021-12-16 07:00
Check if you added Matic chainId in `constants.py` correctly. Also, try to use explicit values instead of `estimate_gas()` call here
https://github.com/uniswap-python/uniswap-python/blob/fa9836eeedd62f8928a7f0a719853d672106aa4f/uniswap/uniswap.py#L1096

**Comment by BlackTurtle123** [comment] 2021-12-16 10:40
> Check if you added Matic chainId in `constants.py` correctly

```
# see: https://chainid.network/chains/
_netid_to_name = {
    1: "mainnet",
    3: "ropsten",
    4: "rinkeby",
    42: "kovan",
    56: "binance",
    97: "binance_testnet",
    137: "polygon",
    100: "xdai",
    137: "matic"
}
```

Still throws the invalid user, is there something else I could have forgotten or should have done?

**Comment by liquid-8** [comment] 2021-12-16 11:02
Did you try to use actual numbers for gas? Something like
`transaction["gas"] = Wei(2000000) `
instead of
`transaction["gas"] = Wei(int(self.w3.eth.estimate_gas(transaction) * 1.2))`

**Comment by BlackTurtle123** [comment] 2021-12-16 11:03
> Did you try to use actual numbers for gas? Something like `transaction["gas"] = Wei(2000000) ` instead of `transaction["gas"] = Wei(int(self.w3.eth.estimate_gas(transaction) * 1.2))`

I adapted this somewhere in the code, but I believe the version from git isnt equal to the latest release in terms off fee code.

**Comment by liquid-8** [comment] 2021-12-16 11:08
That's extremely strange. I have a similar implementation and Matic works totally fine. Could you provide changes you've made for the direct swaps support?

**Comment by BlackTurtle123** [comment] 2021-12-16 11:14
```
        if route is None:
            if self.version == 2:
                # If one of the tokens are WETH, delegate to appropriate call.
                # See: https://github.com/shanefontaine/uniswap-python/issues/22
                if is_same_address(token0, self.get_weth_address()):
                    return int(self._get_eth_token_input_price(token1, Wei(qty), fee))
                elif is_same_address(token1, self.get_weth_address()):
                    return int(self._get_token_eth_input_price(token0, qty, fee))

                route = [token0, token1]
                logger.warning(f"No route specified, assuming route: {route}")
```
                
Maybee I took it to simple since I might not fully understand the whole protocol yet and it's my first experience with those swaps.

**Comment by liquid-8** [comment] 2021-12-16 11:21
I got it imo. You need to modify `_get_tx_params()`

```
def _get_tx_params(self, value: Wei = Wei(0)) -> TxParams:
        """Get generic transaction parameters."""
        return {
            "from": _addr_to_str(self.address),
            "value": value,
            "gasPrice": w3.toHex(w3.toWei(gas_price, 'gwei')), #pass gas_price any way you need
            "nonce": max(
                self.last_nonce, self.w3.eth.get_transaction_count(self.address)
            ),
        }
```
That network doesn't support EIP-1559 yet, but the current web3 tries to send TXs exactly this way by default. When you specify `gasPrice` explicitly, it sends legacy style TX.

**Comment by BlackTurtle123** [comment] 2021-12-16 11:45
> def _get_tx_params(self, value: Wei = Wei(0)) -> TxParams:
>         """Get generic transaction parameters."""
>         return {
>             "from": _addr_to_str(self.address),
>             "value": value,
>             "gasPrice": w3.toWei(gas_price, 'gwei'), #pass gas_price any way you need
>             "nonce": max(
>                 self.last_nonce, self.w3.eth.get_transaction_count(self.address)
>             ),
>         }

```
No route specified, assuming route: ['0x51dE72b17c7bD12E9E6d69eb506a669EB6b5249E', '0xc2132D05D31c914a87C6611C10748AEb04B58e8F']
Traceback (most recent call last):
  File "/home/bnagtega/.config/JetBrains/PyCharm2021.3/scratches/scratch_14.py", line 37, in <module>
    TRADE = quickswap.make_trade(EGG, USDT, 1*10**18, slippage=0.10)  # sell 1 EGG for USDT
  File "/home/bnagtega/.local/lib/python3.10/site-packages/uniswap/decorators.py", line 30, in approved
    return method(self, *args, **kwargs)
  File "/home/bnagtega/.local/lib/python3.10/site-packages/uniswap/uniswap.py", line 406, in make_trade
    return self._token_to_token_swap_input(
  File "/home/bnagtega/.local/lib/python3.10/site-packages/uniswap/uniswap.py", line 682, in _token_to_token_swap_input
    return self._build_and_send_tx(
  File "/home/bnagtega/.local/lib/python3.10/site-packages/uniswap/uniswap.py", line 1087, in _build_and_send_tx
    transaction = function.buildTransaction(tx_params)
  File "/home/bnagtega/.local/lib/python3.10/site-packages/web3/contract.py", line 1079, in buildTransaction
    return build_transaction_for_function(
  File "/home/bnagtega/.local/lib/python3.10/site-packages/web3/contract.py", line 1648, in build_transaction_for_function
    prepared_transaction = fill_transaction_defaults(web3, prepared_transaction)
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
  File "/home/bnagtega/.local/lib/python3.10/site-packages/web3/_utils/transactions.py", line 121, in fill_transaction_defaults
    default_val = default_getter(web3, transaction)
  File "/home/bnagtega/.local/lib/python3.10/site-packages/web3/_utils/transactions.py", line 67, in <lambda>
    'gas': lambda web3, tx: web3.eth.estimate_gas(tx),
  File "/home/bnagtega/.local/lib/python3.10/site-packages/web3/eth.py", line 759, in estimate_gas
    return self._estimate_gas(transaction, block_identifier)
  File "/home/bnagtega/.local/lib/python3.10/site-packages/web3/module.py", line 57, in caller
    result = w3.manager.request_blocking(method_str,
  File "/home/bnagtega/.local/lib/python3.10/site-packages/web3/manager.py", line 198, in request_blocking
    return self.formatted_response(response,
  File "/home/bnagtega/.local/lib/python3.10/site-packages/web3/manager.py", line 170, in formatted_response
    apply_error_formatters(error_formatters, response)
  File "/home/bnagtega/.local/lib/python3.10/site-packages/web3/manager.py", line 70, in apply_error_formatters
    formatted_resp = pipe(response, error_formatters)
  File "cytoolz/functoolz.pyx", line 667, in cytoolz.functoolz.pipe
  File "cytoolz/functoolz.pyx", line 642, in cytoolz.functoolz.c_pipe
  File "/home/bnagtega/.local/lib/python3.10/site-packages/web3/_utils/method_formatters.py", line 580, in raise_solidity_error_on_revert
    raise ContractLogicError('execution reverted')
web3.exceptions.ContractLogicError: execution reverted
```


Is there some way to debug this to see why it's failing still?
Updated the code like you suggested

**Comment by liquid-8** [comment] 2021-12-16 15:37
I can see from this trackback that `estimate_gas()` is still called. Are you sure that you have set a fixed value for `gas` in `_build_and_send_tx()`?

**Comment by BlackTurtle123** [comment] 2021-12-16 15:46
![image](https://user-images.githubusercontent.com/16037736/146403057-ee3d7a62-759d-467e-977a-64b926fb5138.png)

Pretty sure

**Comment by liquid-8** [comment] 2021-12-16 15:51
transaction = function.buildTransaction(tx_params)
        # Uniswap3 uses 20% margin for transactions
        transaction["gas"] = Wei(gas) #fixed value here
        signed_txn = self.w3.eth.account.sign_transaction(
            transaction, private_key=self.private_key
        )

**Comment by BlackTurtle123** [comment] 2021-12-16 22:46
Ended up editing this:

```
TRANSACTION_DEFAULTS = {
    'value': 0,
    'data': b'',
    'gas': lambda web3, tx: Wei(200000),
    'gasPrice': lambda web3, tx: web3.eth.generate_gas_price(tx) or web3.eth.gas_price,
    'maxFeePerGas': (
        lambda web3, tx:
        web3.eth.max_priority_fee
    ),
    'maxPriorityFeePerGas': lambda web3, tx: web3.eth.max_priority_fee,
    'chainId': lambda web3, tx: web3.eth.chain_id,
}
```

Tx succesfully processed. Thanks for ur support

**Comment by liquid-8** [comment] 2021-12-17 06:16
That's a good sign, you're about to finish. I would consider removal `maxFeePerGas` and `maxPriorityFeePerGas` from TX params until they roll out EIP-1559 to their mainnet. Also, `gas` actual value can be a problem because some contracts require gas amounts like 2mln, though actual spendings are pretty the same. As well, I personally refused the idea to use `generate_gas_price()` because it works too slow.

**Comment by BlackTurtle123** [comment] 2021-12-17 08:40
Mmmm i removed those, still same error.

But it's such a generic error so no clue why it keeps pop up, unless I am missing something

**Comment by liquid-8** [comment] 2021-12-17 13:35
Seems like I've found it. Look at the failed TX
https://polygonscan.com/tx/0x535064eddbb6575d2eec85c693415a304f4beca286faba5f3194126dd22f8261
In fact, the route is
51de72b17c7bd12e9e6d69eb506a669eb6b5249e #EGG
0d500b1d8e8ef31e21c99d1db9a6444d3adf1270 #WMATIC
c2132d05d31c914a87c6611c10748aeb04b58e8f #USDT

Just press "Decode input" to ensure. From what i see, you've modified `_eth_to_token_swap_input()` to use direct routes, but here `_token_to_token_swap_input()` is called because both tokens != wmatic. So, you just need to make the same changes in every `*_swap_*()` method, and then everything is gonna be ok. And no, there is no way you've made it already as the router's method `swapExactTokensForTokens()` is called with [t0, weth, t1] route, which is hardcoded in the library at the moment.

**Comment by BlackTurtle123** [comment] 2021-12-17 13:41
Hello,
you are right!
You are my hero now hehhe.

Thanks for your patience and support

**Comment by liquid-8** [comment] 2021-12-17 18:35
That's ok. Feel free to close this issue.

**Comment by snarflakes** [comment] 2022-10-13 01:31
> First, that's not a bug actually because Matic is a different network. There is no need to add this middleware on the ETH mainnet. Your workaround is totally fine. In fact, that's how it is supposed to be.


I'm getting the same extraDataLengthError but I'm just trying to swap using polygon uniswapV3: Where do we insert these lines in the uniswap modules? In the constant.py module?

"w3.middleware_onion.inject(geth_poa_middleware, layer=0)"

Thanks much!

**Closed** 2022-10-19 09:19 UTC
Labels: bug
